// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_6N2Afgly1744Wvq_8JHFU03Vd8h3Co',
    appId: '1:491375275011:web:35db2fb06b84db11a47236',
    messagingSenderId: '491375275011',
    projectId: 'vize-030120006',
    authDomain: 'vize-030120006.firebaseapp.com',
    storageBucket: 'vize-030120006.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByUPTP-1nYHQPK2uVNXPYeEcO2K3exuL4',
    appId: '1:491375275011:android:fc353e478c6bf7a3a47236',
    messagingSenderId: '491375275011',
    projectId: 'vize-030120006',
    storageBucket: 'vize-030120006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-uLwSWzUcTs8d7lIB8W8waPf_-m-NeM',
    appId: '1:491375275011:ios:43496926bcc98b76a47236',
    messagingSenderId: '491375275011',
    projectId: 'vize-030120006',
    storageBucket: 'vize-030120006.appspot.com',
    iosClientId: '491375275011-9ssfmnuealn4pm2c5u430u15t32afol3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt-uLwSWzUcTs8d7lIB8W8waPf_-m-NeM',
    appId: '1:491375275011:ios:43496926bcc98b76a47236',
    messagingSenderId: '491375275011',
    projectId: 'vize-030120006',
    storageBucket: 'vize-030120006.appspot.com',
    iosClientId: '491375275011-9ssfmnuealn4pm2c5u430u15t32afol3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
